wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.20
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1763845222.510464
    t:
      1:
      - 1
      - 30
      - 50
      - 55
      - 79
      3:
      - 13
      - 23
      4: 3.8.20
      5: 0.14.2
      8:
      - 5
